[package]
name = "ivo"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = { path = "../geo" }
rustc-hash = "2"

[dev-dependencies]
noise = "0.9"
rand = "0.8"
sketch_utils = { path = "../sketch-utils" }
