[package]
name = "ivo"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = {path = "../geo"}
rustc-hash = "1.1"

[dev-dependencies]
noise = "0.7"
rand = "0.8"
sketch_utils = { path = "../sketch-utils" }
