[package]
name = "buzz"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2018"

[dependencies]
geo = { path = "../geo"}
image = "0.23"
rand = "0.7"
rand_xorshift = "0.2"
rayon = "1.5"

