[package]
name = "buzz"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2021"

[dependencies]
geo = { path = "../geo"}
image = "0.24"
rand = "0.8"
rand_xorshift = "0.3"
rayon = "1.5"
