[package]
name = "buzz"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.22"
rand = "0.7"
rayon = "1.2"
geo = { path = "../geo"}

[dev-dependencies]
rand_xorshift = "0.2"
